### ISSUE TITLE
Test do not work because of an "outdated" dependency on Suggestion Handler

### ISSUE THREAD

**Issue by tkurz** [RBMHTechnology/vind#1]
In `vind/backend/solr/src/main/resources/solrhome/core/conf/solrconfig.xml` there is still a dependency on the "outdated" suggestion handler. Therefor the tests does not work. This could be fixed by integration the suggestion-handler `utils/suggestion-handler` to the classpath.

**Comment by ja-fra** [comment]
fixed with ce286b0
