### ISSUE TITLE
Improve error message when creating an instance `SearchServer`

### ISSUE THREAD

**Issue by seakayone** [RBMHTechnology/vind#168]
Vind does not produce meaningful error messages and thus it is very hard to track down the actual problem why a  `SearchServer` cannot be created.

In my setup (using solr as master and elastic as slave) I have have had the same exception for many different reasons.

The exception happens when calling `SearchServer.createInstance()` is:
```
java.lang.RuntimeException: No SearchServer of class [com.rbmhtechnology.vind.elasticsearch.backend.ElasticServerProvider] in classpath
```

The reasons why this happens can be :
* The actual classpath does not have the dependencies for solr/elastic
* The actual classpath does have the dependencies, but in nonmatching versions (i.e. lucene is used for elastic and solr but not all versions are compatible)
* The actual classpath does have the dependencies, and in matching versions, but the configuration of the elastic search is incorrect

**Comment by seakayone** [comment]
One way to improve this could be here: https://github.com/RBMHTechnology/vind/blob/master/api/src/main/java/com/rbmhtechnology/vind/api/SearchServer.java#L78

This is the place where the exception is thrown. As a first step we could use the cause to enhance/change the thrown exception.

**Comment by alfonso-noriega** [comment]
We actually had a higher level of login there but, as the service loader runs through all the available SearchServerProviders trying to instantiate one that is valid, there are many logs which are not completely relevant. So the challenge is to identify which errors are relevant for the current configuration and/or limit as much as possible the errors produce by just trying to instantiate relevant SearchServerProviders.

**Comment by alfonso-noriega** [comment]
Vind 3.0.7  contains improved error messages
