### ISSUE TITLE
Add configuration support via environment variables

### ISSUE THREAD

**Issue by aremann** [RBMHTechnology/vind#35]
Currently the vind configuration is mostly done via a properties file. To ensure the cloud-readiness of the library the configuration via environment variables is needed.

Example:
```
VIND_SERVER_SOLR_CLOUD=true
VIND_HOST=...
...
```

**Comment by tkurz** [comment]
Env Variables are now supported + the configuration is described in more detail at
https://github.com/RBMHTechnology/vind/blob/develop/docs/step6.md
