### ISSUE TITLE
Precendence of configuration settings using environment variables

### ISSUE THREAD

**Issue by seakayone** [RBMHTechnology/vind#38]
According to the documentation of vind 1.2 :
> The properties are overwritten following the ordering: Default Properties < Environment Variables < Property File

This behaviour is unlike e.g. [Spring](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) and typesafe config which do “Default Properties < Property File < Environment Variables”.

This means we have to provide all settings in every environment as environment variables as we cannot simply provide a property file for development which can be overwritten using environment variables. For productive deployment environment variables are easy to handle but locally one might want to provide defaults using a file instead of manually having to configure IDE env vars.

**Comment by seakayone** [comment]
Do you think it would be possible/make sense to change the presedence to “Default Properties < Property File < Environment Variables”?

**Comment by tkurz** [comment]
Taking a closer look and compare it to standard behavior in other frameworks (e.g. Spring Boot) I think it is better to change the ordering. Thanks @seakayone for the hint.

**Comment by seakayone** [comment]
Wonderful, thanks.
