### ISSUE TITLE
Support Term Query Parser for huge ID searches

### ISSUE THREAD

**Issue by mhaslauer** [RBMHTechnology/vind#45]
There are some use cases where we want to search for a large set of document IDs but there is no other search filter that identifies these specific group of documents. Hence we need to search via the IDs only, to offer the user further possibilities to sort, page and apply additional filters.

The current problem is, that this group of document IDs can be up to 5000. In the furture, this may be even extended up to 30-50k.

As the standard query parser only supports up to 1024 boolean clauses, please offer the possibility to use the term query parser instead.

**Comment by alfonso-noriega** [comment]
A new filter _TermsQueryFilter_ has been created to solve this issue. The filter is added as any other filter and can be combined with a fulltext search or other filters.
To instantiate this filter there are two ways:

- By using the Filter clas and it methods to instantiate filters: `Filter.terms(feldDescriptor, scope, valueq, value2,...);`

- By using the FieldDescriptors method helpers to instantiate filters: `fieldDescriptor.terms(scope, value1, valu3,...);`
