### ISSUE TITLE
Wrong filters in 1.2.3

### ISSUE THREAD

**Issue by stefan-sachs** [RBMHTechnology/vind#66]
With vind 1.2.1 the following search
```
{"q":"*","filter":"((static_status='passive') OR (static_status='active')) AND ((static_partitionID='MV-1HP6U6PQS1W11') OR (static_partitionID='MV-1HP6TNXVH1W11') OR (static_partitionID='MV-1HP6UG2V51W11'))","timeZone":"null","sort":[{'direction':'Desc','field':'static_recordLastUpdateTimestamp'}],"result":{"sliceSize":21,"offset":0},"nestedDocSearchFlag":false,"nestedDocOp":"OR","nestedDocFactory":null,"nestedDocSearch":null,"facetFlag":false,"facetMinCount":1,"facetLimit":10,"facet":{},"geoDistance":null,"searchContext":"null","strictFlag":true}
```
resulted in those filters (only status and partitionID are relevant here)
```
&fq=((dynamic_multi_stored_filter_string_static_status:"active"+OR+dynamic_multi_stored_filter_string_static_status:"passive")+AND+(dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6UG2V51W11"+OR+dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6TNXVH1W11"+OR+dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6U6PQS1W11"))
``` 
which is the expected fq. 

When using vind 1.2.3 the same code produces this search
```
{"q":"*","filter":"((static_status='active') OR (static_status='passive')) AND ((static_partitionID='MV-1HP6U6PQS1W11') OR (static_partitionID='MV-1HP6UG2V51W11') OR (static_partitionID='MV-1HP6TNXVH1W11'))","timeZone":"null","sort":[{'direction':'Desc','field':'static_recordLastUpdateTimestamp'}],"result":{"sliceSize":21,"offset":0},"nestedDocSearchFlag":false,"nestedDocOp":"OR","nestedDocFactory":null,"nestedDocSearch":[],"facetFlag":false,"facetMinCount":1,"facetLimit":10,"facet":{},"geoDistance":null,"searchContext":"null","strictFlag":true}
```
The filters in the search are the same as before (except the order). However, the generated fq for solr is broken since it now generates this:
```
&fq=dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6UG2V51W11"+OR+dynamic_multi_stored_filter_string_static_status:"passive"+OR+dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6U6PQS1W11"+OR+dynamic_multi_stored_filter_string_static_status:"active"+OR+dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6TNXVH1W11"
```

**Comment by alfonso-noriega** [comment]
It seems to be an issue in the process of normalization of the filters. The expected normalized form should be: 
`(dynamic_multi_stored_filter_string_static_status:"active"+AND+dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6UG2V51W11")+OR+(dynamic_multi_stored_filter_string_static_status:"active"+AND+dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6TNXVH1W11")+OR+(dynamic_multi_stored_filter_string_static_status:"active"+AND+dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6U6PQS1W11")+OR+(dynamic_multi_stored_filter_string_static_status:"passive"+AND+dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6UG2V51W11")+OR+(dynamic_multi_stored_filter_string_static_status:"passive"+AND+dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6TNXVH1W11")+OR+(dynamic_multi_stored_filter_string_static_status:"passive"+AND+dynamic_multi_stored_filter_string_static_partitionID:"MV-1HP6U6PQS1W11")`
