### ISSUE TITLE
Provide Docker-Image for Solr Backend

### ISSUE THREAD

**Issue by ja-fra** [RBMHTechnology/vind#67]
In order to simplify testing vind integration with a "real" backend, it would be convenient to provide a ready-to-use docker image containing the vind-schema and -extensions.

**Comment by tkurz** [comment]
Docker image is now on dockerhub https://hub.docker.com/r/redlinkgmbh/vind-solr-server/builds/ .
Versions of `redlinkgmbh/vind-solr-server` are aligned with Vind versions.

**Comment by tkurz** [comment]
Repository is here https://github.com/redlink-gmbh/vind-solr-server

**Comment by tkurz** [comment]
The Documentation has been extended, too. See https://github.com/RBMHTechnology/vind/commit/720fca5c66bd7e3997cce037483f890c65ef1dee
